# Default values for devops-infra.
namespace: devops-demo

sqlserver:
  image: mcr.microsoft.com/mssql/server:2022-latest
  replicas: 1
  storage: 10Gi
  secretName: sqlserver-secret
  sealedPassword: AgA58JTq0jidRYh6+o4b9YJr/PBiq8RDQ052wZBZ4ugT8hLnJ5hqkj/1xSebaXCtwjLRIVK1DxBUwkzFTxPNlrn0CheZgcxx6A52lYITSbcyiVaR5BksjPSkhbYhoLX071uTXGUx3cJGoA/1czxUuW+IRcQaogg36ARARL5wsaG88wYILtDMwXCp9WFmNtBhNhaSrbidjQQoN6dpn3584n0BTRHbz/pfO1WofV6oLU8iYACusKGM7clE31jR7hcjKgxnBoSU+1X0l9lLV+tKa0sY8NwGySUKV845+EP1ux1n2sdnW3h3J4x0MC9LNauEr6pViwkK1vxVMcL+2ehXfhV2ygLG2Ejg4VTCZhQQ9ZQ/7LbmcuYNttmGXbddEy6DPZk0NDiExU4SfuxMK+QerkFQ1oY87A7YIOQ2FIiDnMwmrVl1+oIbp2U4BsA1QbvMy+nJ8lnmmpfCU+NCpZ5PLj0Lu7jFPAeM48OjK59gahZ2tJGGbaYKmgGV88gOeJrd6UtHIYxeOMMkYwryALRrfFODeoG0feX+xiHJz+3J7CCz36OOlIL2Mv8v/Zh9WXjl1UyQPywCPwzUvjkVPk7PRGOLpoelSIwGYD77Np7coCGvV4TRvxJFLgRCNDirb1Z2hcj3k/Oe2KBRTX631CE8b3SwwM+DBcctfHL7X+L0ecoEsY/CSqXwouBDTmHM0qyEYF3aQ8265H4WQF3LbXLiNO/IrDTkLtQitnolB/2eRp9LzA==

webapp:
  sqlserverSecretName: webapp-sqlserver-secret
  image: mcr.microsoft.com/dotnet/samples:aspnetapp
  replicas: 1

mongodb:
  image: mongo:6
  replicas: 1
  storage: 5Gi

redis:
  image: redis:7
  replicas: 1
  storage: 2Gi
  