---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.sqlserver.secretName }}
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    SA_PASSWORD: {{ .Values.sqlserver.sealedPassword }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Values.sqlserver.secretName }}
      namespace: {{ .Values.namespace }}
