apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqlserver
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "sqlserver"
  replicas: {{ .Values.sqlserver.replicas }}
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      securityContext:
        fsGroup: 10001
      containers:
      - name: sqlserver
        image: {{ .Values.sqlserver.image }}
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.sqlserver.secretName }}
              key: SA_PASSWORD
        volumeMounts:
        - name: sqlserver-persistent-storage
          mountPath: /var/opt/mssql
  volumeClaimTemplates:
  - metadata:
      name: sqlserver-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.sqlserver.storage }}
