---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webapp-sqlserver-secret
  namespace: devops-demo
spec:
  encryptedData:
    SA_PASSWORD: AgAQRPoj89P+zuNw5wN3oNoSlEnpEF7lCyKlm/04DQFmkcS+na8SZYqbvA/jE+rvlVmECEtXvN9mHY7y1gSRVeHqJlCBiIZDzqsR8F+0OtEZ8E9kdPJQWNB/XQ0RQktiEn4aaZzvEFD0J1GtP1rvpVMiMEtItGWpjiPAHW628ksIzEzRpM2jzTELeFRnqJQBljkQyfoXQ7cTBEhLR4/e1m+03zqKPDVzVyPOX3AjOdjc/rislc2tm7a1M3owetJmmN6h6/DeAJh3EOGF+S5u+USe4wWcKNc5c27ioW04dWueocdBB4D8l8y05z7b38F+NGJMfbb7tG282e1/rHoUpLP+z09Oab2j3gREoc9n799NfXL9C8ENF/j6lH181BEoUpwbOpHCljgITveC+0iUrf58Jj1LiErByfSYx739kXrdgBFrgzZoa3DYhJOSwPrq3WB1vv2nSTK+l0eXC2jPpEFeQbfcLUMm0/7B6IrSWLcQdtkcf39SI1dUGNUbngGAd8YuVi4DSS0xmraPwyh0KjFew/hK/013Tcjw7C4zp+loGGNQg4lk62iaeBLqj6rdfRUghyZBE/9KHM1GVAc7BMDKEkQU4Dkja5trT1d/Z3ujNQh+poRvPNhg6a65x5wzMj5DII3OQ+hPFjPfVPiNscBUZiyqJPgSTfYja/pqI2K0IrVUTdPfsVccdFX9CCaL29O3+YbezYSicFMDhffb1BV+0kHWN7UFj3v1EwxeEnycUg==
  template:
    metadata:
      creationTimestamp: null
      name: webapp-sqlserver-secret
      namespace: devops-demo
