apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.webapp.serviceType }}
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: webapp
