---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: webapp-sqlserver-secret
  namespace: devops-demo
spec:
  encryptedData:
    SA_PASSWORD: AgAUzy/OpCZ+I8qQSR24XTLaoDAaTPpHbB2R8kbP37HqQf6YfedwbuH44QwkszvlEjonRWSaYKSY5zzv1pia3poB0iFK/eQ0LQU1jxzUpy0W42MdQ5sdtHVYXzNG8D5UtFPUW5Rb1I0kDwN55GkOMkobFunXPBDHGmHXyTfcouh1rqWehGvkpSzQYoBxZm5vp3xMTgCM9Hp/Bq/FXGGPSMYq4oLm1ALuW7Tc/e/M+dZ3Zlm2VVoCVLGSxiMS+cYGGsRuKq7sscH7hvDnEIkU3SpMUltFFIod9UaKEMKZ12e+Zy1n+IZyC/YnDsCeoTM25sKjSS2VupV0t8DWWQwR1HXESE8m7XfMjxJx6pwmoCbheWqLsl4vlIyAeEoyUDBMXH4U05CXlFvfG4sgbE0n0cpFu4G23cELDEzlTS1ZgRheO4G0jqJW2XpN7C2grfNMQ2CiEbSkSHGLntVzdx4KMPo0HpBOVDDdO+92NqlBnQ5LYHTdn8gDzsWiQrjp4UJztQsTne+GENyTqgZxcmsZd4cScc70s62+EaZcAWK4TyrD3qNHZ/+lCototb1EDSgbDtSWw2vro7jDLfF6fhqAVKqcYu6N3Bjtp0z1bCyRCNoH39JlPqasOYggPAUoV1+njkok3XYVizOLPy4emVro738xO6H0zBZ83p/3L6yCanv7yUQNdumU/JMFdO8FIWdwOR7F8Q/QKfHq1wQQxxVljBmWm7hnFPmwl83i/RgBnfclPQ==
  template:
    metadata:
      name: webapp-sqlserver-secret
      namespace: devops-demo
    type: Opaque
