apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webapp-tls
  namespace: devops-demo
spec:
  secretName: webapp-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: aks.infrahub.systems
  dnsNames:
    - aks.infrahub.systems
